config/routes.rb
Rails.application.routes.draw do
	get '/about', controller: 'news', action: 'about'
	get '/privacy', controller: 'news', action: 'privacy'
	
	resources :dungeons do
		get 'json/normal' => "dungeons#get_normal_dungeons", on: :collection
		get 'json/special' => "dungeons#get_special_dungeons", on: :collection 
		get 'json/technical' => "dungeons#get_technical_dungeons", on: :collection 
		get 'json/multiplayer' => "dungeons#get_multiplayer_dungeons", on: :collection
	end
	
	resources :ml_ratings, only: [:create]
	
	resources :monster_links
	
    resources :news

	resources :c_ratings, except: [:edit, :update, :destroy, :new, :show]
	resources :c_ll_ratings, except: [:edit, :update, :destroy, :new, :show]
		
	resources :comments,  except: [:edit, :update, :new, :show]
	resources :comment_lls,  except: [:edit, :update, :new, :show]

	resources :votes, except: [:edit, :update, :destroy, :new] do
		get 'statistics' , controller: 'votes', action: 'statistics', on: :collection 
	end
	resources :vote_lls, except: [:edit, :update, :destroy, :new]

	resources :monsters, except: [:destroy, :new, :create, :update, :edit] do
		get 'json/tags', controller: 'monsters', action: 'tags_json', on: :collection 
		get 'json/typeahead', controller: 'monsters', action: 'typeahead_json', on: :collection 
		get 'json/subs/:id', controller: 'monsters', action: 'subs_json', on: :collection 
		get 'json/graph', controller: 'monsters', action: 'graph_json', on: :collection
		get 'detail' , controller: 'monsters', action: 'detail', on: :collection 
		get 'tag', controller: 'monsters', action: 'add_tag'
		get 'tag/pair', controller: 'monsters', action: 'add_pair_tag'
		get 'tags', controller: 'monsters', action: 'search', on: :collection
		get 'tags/update', controller: 'monsters', action: 'tag_update', on: :collection
		get 'questionable', controller: 'monsters', action: 'questionable', on: :collection
		get 'autosuggestion', controller: 'monsters', action: 'auto_suggestion'
	end

	devise_for :users
	
	
	match '/static/img/monsters/:size/:id.:basename.png' => "monsters#image_proxy", via: [:get]
	
	root 'news#index'

end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  require 'open-uri'
  require 'open_uri_redirections'
  before_action :cache_data
  #before_action :set_monster, only: [:auto_suggestion]
  before_action :fetch_both, only: [:detail, :graph_since_json, :graph_monthly_json, :graph_count_json, :graph_weight_json, :graph_json ]
  before_action :authenticate_user!, only: [:add_tag, :add_pair_tag, :tag_update]
  respond_to :html
  
  def questionable
	Rails.cache.fetch("questionable_outliers", expires_in: 15.minutes) do
			Vote.outliers(Rails.application.config.vote_display_default, "ls")
	end
	Rails.cache.fetch("questionable_low_count", expires_in: 15.minutes) do
			Vote.low_count(Rails.application.config.vote_display_default, "ls")
	end
	Rails.cache.fetch("questionable_low_rating", expires_in: 15.minutes) do
			Vote.low_rating(Rails.application.config.vote_display_default, "ls")
	end
	Rails.cache.fetch("questionable_low_rarity", expires_in: 15.minutes) do
			Vote.find_monster_in(fetch_low_rarity_json, Rails.application.config.vote_display_default, "ls")
	end
	#@outliers = Vote.outliers(Rails.application.config.vote_display_default, "ls")
	#@low_count = Vote.low_count(Rails.application.config.vote_display_default, "ls")
	#@low_rating = Vote.low_rating(Rails.application.config.vote_display_default, "ls")
	@outliers = Rails.cache.fetch("questionable_outliers")
	@low_count = Rails.cache.fetch("questionable_low_count")
	@low_rating = Rails.cache.fetch("questionable_low_rating")
	@low_rarity = Rails.cache.fetch("questionable_low_rarity")
  end

  def fetch_low_rarity_json
	monsters = Rails.cache.fetch("monster")
	results = Array.new
	monsters.each do |m|
		if m["rarity"] < 5 then results.push(m["id"]) end
	end
	return results
  end
  
  def image_proxy
	remote_url = Rails.application.config.img_path_monsters + "#{request.path}"
	local_url = "public#{request.path}"
  
	if not File.exist? local_url
		IO.copy_stream(open(remote_url, :allow_redirections => :safe), local_url)
	end
 
	send_file local_url, type: 'image/png', disposition: 'inline'
  end
	
  def search
	@title = "Tags"
	@tags = ActsAsTaggableOn::Tag.order(:name)
	@selected = params[:tags]
	if @selected != nil and @selected.size > 0
		monsters = Monster.tagged_with(@selected, :on => :tags)
		if monsters != nil and monsters.length > 500
			monsters = monsters[0..499]
			flash.now[:alert] = 'Showing first 500 results. Add more tags to narrow search.'
		end
		@monsters = fetch_monster_json_by_array(monsters)
		if @monsters != nil then @monsters = @monsters.sort_by { |hash| hash['element'].to_i } end 
	end
  end
  
  def index
	@title = "Summary"
	@latestVotes = Vote.order(created_at: :desc).limit(Rails.application.config.fp_display_max_monsters)
	@latestVotesLl = VoteLl.order(created_at: :desc).limit(Rails.application.config.fp_display_max_monsters)
	
	topMonstersArray = Vote.recent_top(Rails.application.config.vote_display_default)
	@topMonsters = Array.new
	topMonstersArray.each do |m|
		@topMonsters.push([fetch_monster_by_id(m[0]),m[1]])
	end
	
	@topUsers = User.top
	@latestComments = Comment.latest
	@latestCommentsLl = CommentLl.latest
  end
  
  #Shows a particular monster from JSON. Input parameter is params[:id]
  def show
	@monster = fetch_monster_by_id(params[:id])

	#Make sure monster was fetched
	if @monster != nil
		update_monster_name_with_json(@monster)
		@monster.url = fetch_monster_url_by_id_json(@monster.id)
		
		@title = @monster.id.to_s
		
		@subs = Array.new
		#Get suggested subs
		@subs_list = @monster.subs
		@subs_list = @subs_list.sort_by { | x | x[:score] }.reverse
		@subs_list.each do |s|
			sub = fetch_monster_by_id(s[:id])
			if sub != nil
				sub.avg = round?(s[:score])
				sub.avg_count = @monster.vote_count(sub.id,"ls")
				sub.url = fetch_monster_url_by_id_json(sub.id)
				if user_signed_in? and user_voted_default_month(@monster.id,sub.id,"ls")
					sub.user_score = fetch_user_vote_by_default_month(@monster.id, sub.id,"ls").score
				end
				@subs.push(sub)
			end
		end
		
		@leaders = Array.new
		#Get suggested leaders
		@leaders_list = @monster.leaders
		@leaders_list = @leaders_list.sort_by { | x | x[:score] }.reverse
		@leaders_list.each do |l|
			leader = fetch_monster_by_id(l[:id])
			if leader != nil
				leader.avg = round?(l[:score])
				leader.avg_count = leader.vote_count(@monster.id,"ls")
				leader.url = fetch_monster_url_by_id_json(leader.id)
				if user_signed_in? and user_voted_default_month(leader.id,@monster.id,"ls")
					leader.user_score = fetch_user_vote_by_default_month(leader.id,@monster.id,"ls").score
				end
				@leaders.push(leader)
			end
		end
		
		@ll = Array.new
		@ll_list = @monster.ll_list
		@ll_list = @ll_list.sort_by { | x | x[:score] }.reverse
		@ll_list.each do |l|
			leader = fetch_monster_by_id(l[:id])
			if leader != nil
				leader.avg = round?(l[:score])
				leader.url = fetch_monster_url_by_id_json(leader.id)
				leader.avg_count = @monster.vote_count(leader.id,"ll")
				if user_signed_in? and user_voted_default_month(@monster.id,leader.id,"ll")
					leader.user_score = fetch_user_vote_by_default_month(@monster.id,leader.id,"ll").score
				end
				@ll.push(leader)
			end
		end
		
		#Get other details
		@active_skill = fetch_active_skill_by_id_json(@monster.id)
		@leader_skill = fetch_leader_skill_by_id_json(@monster.id)
		@awakenings = fetch_awakenings_by_id_json(@monster.id)
		@related = append_monster_url(get_all_evo(@monster.id))
		@tags = @monster.tag_list.sort
		@links = @monster.monster_links.order(updated_at: :desc)
		
		tags = @monster.tag_list.sort
		
		#Rarity
		@rarity = "rarity: over 5"
		
		#Elements
		@attr_main = tags.select {|tag| tag.include? 'attr main:'}[0]
		if @attr_main != nil then 
			@elem_main = @attr_main.split('attr main: ')[1]
			@attr_elem1 = "attr: " + @elem_main
		end
		@attr_sub = tags.select {|tag| tag.include? 'attr sub:'}[0]
		if @attr_sub != nil
			@elem_sub = @attr_sub.split('attr sub: ')[1] 
			@attr_elem2 = "attr: " + @elem_sub
		end
		
		if @attr_main != nil then @check_main = "checked" end
		@check_sub = ""
		@check_elem1 = ""
		@check_elem2 = ""
		@check_rarity = "checked"
		
		#Type
		@type = tags.select {|tag| tag.include? 'type:'}
		@check_type = Array.new
		@type.each do |t|
			type = t.split('type: ')[1]
			if @leader_skill != nil
				if @leader_skill["effect"].downcase.include? type then @check_type.push(t) end
			end
		end
				
		#Awakenings
		@check_awoken_skills = Array.new
		@awoken_skills = tags.select {|tag| tag.include? 'awoken skill:'}
		if not @awoken_skills.include? 'awoken skill: recover bind' then @awoken_skills.push('awoken skill: recover bind') end
		if not @awoken_skills.include? 'awoken skill: resistance-bind' then @awoken_skills.push('awoken skill: resistance-bind') end
		if not @awoken_skills.include? 'awoken skill: two-pronged attack'
			@awoken_skills.push('awoken skill: two-pronged attack')
		else
			@check_awoken_skills.push('awoken skill: two-pronged attack')
		end
		if @elem_main != nil and not @awoken_skills.include? 'awoken skill: enhanced ' + @elem_main + ' att.'
			@awoken_skills.push('awoken skill: enhanced ' + @elem_main + ' att.')
		elsif @elem_main != nil and @awoken_skills.include? 'awoken skill: enhanced ' + @elem_main + ' att.'
			@check_awoken_skills.push('awoken skill: enhanced ' + @elem_main + ' att.')
		end
		if @elem_sub != nil and not @awoken_skills.include? 'awoken skill: enhanced ' + @elem_sub + ' att.'
			@awoken_skills.push('awoken skill: enhanced ' + @elem_sub + ' att.')
		elsif @elem_sub != nil and @awoken_skills.include? 'awoken skill: enhanced ' + @elem_sub + ' att.' and @elem_sub != @elem_main
			@check_awoken_skills.push('awoken skill: enhanced ' + @elem_sub + ' att.')
		end
		@awoken_skills.sort!

	else
		render_404; return;
	end
	
    respond_with(@monster)
  end
  
  def auto_suggestion
	filter = params["filter"]
	
	if filter == nil then return end
	
	@monster = Monster.find(params["monster_id"])
	if @monster != nil
		#Get tags
		tags = @monster.tag_list.sort
		
		#Get elements
		attr_main = tags.select {|tag| tag.include? 'attr main:'}[0] #attr main: fire
		
		if attr_main == nil then return end
		
		if attr_main != nil then elem_main = attr_main.split('attr main: ')[1] end #fire
		attr_sub = tags.select {|tag| tag.include? 'attr sub:'}[0] #attr sub: water
		if attr_sub != nil then elem_sub = attr_sub.split('attr sub: ')[1] end #water
		
		exclude = ["type: awoken skill material","type: enhance material","type: evo material"] #Exclude all tags in this array
		
		#Get Leader Skill
		leader_number_colors = 0 #Leader requires 0 colors to activate skill
		
		color_match = tags.grep(/leader skill: color match - [1-9] colors/) #Find tag which determines number of colors the leader needs
		if color_match.length == 1 then #If a match was found and an array was returned with exactly 1 result
			leader_number_colors = color_match[0].split('leader skill: color match - ')[1].split(' colors')[0] #Get the number from the tag
			if is_number? leader_number_colors then #If it is a number
				leader_number_colors = leader_number_colors.to_i #Convert from string to int
				leader_colors = tags.grep(/leader skill: color match - [a-z]/).each do |c| c.gsub!('leader','active').gsub!('color match','change board') end #Get all of the colors this leader requires
			end
		end
		
		#Filters
		
		#Utility
		utility = [
			'active skill: damage reduction',
			'active skill: defense reduction',
			'active skill: delay',
			'active skill: avoid damage',
			'active skill: bind recovery',
			'active skill: poison damage',
			'active skill: atk buff'
		]
		
		#Orb Change
		orb_change = ['active skill: change orbs - ' + elem_main]
		if attr_sub != nil then orb_change.push('active skill: change orbs - ' + elem_sub) end
		orb_change.push('active skill: spawn')
		orb_change.push('active skill: skyfall')
		
		#Board Change
		board_change = Array.new
		if leader_number_colors == 0

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/monsters/_detail.html.erb
<div>
	<div class="panel panel-default monster details">
		<div class="center-text panel-heading monster">
			<strong>Leader</strong>
		</div>
		<div class="panel-body">
			<%= link_to image_tag(Rails.application.config.img_path_monsters + @leader_details["image60_href"].to_s, :border => 0, :title => @leader.id.to_s + ". " + @leader.name), monster_path(@leader.id) %>
		</div>
	</div>
	<div class="panel panel-default monster details">
		<div class="center-text panel-heading monster">
			<strong>Sub</strong>
		</div>
		<div class="panel-body">
			<%= link_to image_tag(Rails.application.config.img_path_monsters + @sub_details["image60_href"].to_s, :border => 0, :title => @sub.id.to_s + ". " + @sub.name), monster_path(@sub.id) %>
		</div>
	</div>
	<div class="panel panel-default monster details summary">
		<div class="center-text panel-heading monster">
			<strong>Details</strong>
		</div>
		<div class="panel-body">
			<table width=100% height=100%>
				<tr>
					<td><span class="badge">Current</span></td>
					<td><span class="label label-<%= rating_style(@score) %>"><%= round?(@score) %> out of <%= Rails.application.config.vote_rating_max %></span><span class="label label-primary"><%= @votes %> votes</span></td>
				</tr>
				<tr>
					<td><span class="badge">All Time</span></td>
					<td><span class="label label-<%= rating_style(@score_all) %>"><%= round?(@score_all) %> out of <%= Rails.application.config.vote_rating_max %></span><span class="label label-primary"><%= @votes_all %> votes</span></td>
				</tr>
			</table>
		</div>
	</div>
	<div class="panel panel-default monster tags details">
		<div class="center-text panel-heading monster tags">
			<strong>Pairing Specific Tags</strong>
		</div>
		<div class="panel-body tags">
			<%= form_tag(monster_tag_pair_path(@leader.id, sub_id: @sub.id), method: "get", remote:true ) do %>
				<div>
					<p><select id="tags-modale" style="width:100%;" disabled multiple="true" name="tags[]" class="tags select2">
					<% @leader.tag_list_on("sub_" + @sub.id.to_s).each do |t| %>
						<option selected="selected"><%= t %></option>
					<% end %>
					</select></p>
				</div>
				<% if user_signed_in? %>
					<div id="edit-modale" class="tags  button-container col-xs-3">
						<button type="button" id="edit-tags-modale" class="btn btn-default tags" aria-label="Left Align">Edit</button>
					</div>
					<div id="update-modale" class="tags  button-container col-xs-3">
						<%= submit_tag "Update", id:"update-tags-modale", class: "tags btn btn-default" %>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

<script>
	chart1(<%= @leader.id %>,<%= @sub.id %>,['since','monthly','weighted'],'#chart1','Ratings',1,<%= Rails.application.config.vote_rating_max %>);
	chart1(<%= @leader.id %>,<%= @sub.id %>,['count'],'#chart2','Ratings Count',null,null);
</script>

<ul class="nav nav-tabs">
  <li id="statistics" role="presentation" class="active"><a href="#">Statistics</a></li>
  <li id="comments" role="presentation"><a href="#">Comments</a></li>
  <li style="display: none;" id="history" role="presentation"><a href="#">History</a></li>
</ul>
<div id="statistics" class="page-tab">
	<div id="chart1" style="min-width: 310px; height: 300px; margin: 0 auto"></div>
	<div id="chart2" style="min-width: 310px; height: 300px; margin: 0 auto"></div>
</div>
<div id="comments" class="page-tab">
	Comments to be implemented
</div>
<div id="history" class="page-tab">
	History
</div>
<%= render partial: 'modale' %>

app/views/monsters/_modale.html.erb
<script>
$(document).ready(function(){
	$('ul.nav-tabs').show();
	$('div#comments.page-tab').hide();
	$('div#history.page-tab').hide();
	
		$('.nav-tabs li#statistics').click(
		function() {
			$('div.page-tab').hide();
			$('.nav-tabs li').removeClass("active");
			$('.nav-tabs li#statistics').addClass("active");
			$('div#statistics.page-tab').show();
		}
	)
	$('.nav-tabs li#comments').click(
		function() {
			$('div.page-tab').hide();
			$('.nav-tabs li').removeClass("active");
			$('.nav-tabs li#comments').addClass("active");
			$('div#comments.page-tab').show();
			
		}
	)

	$('.nav-tabs li#history').click(
		function() {
			$('div.page-tab').hide();
			$('.nav-tabs li').removeClass("active");
			$('.nav-tabs li#history').addClass("active");
			$('div#history.page-tab').show();
		}
	)
	$('#edit-tags-modale').click(
		function() {
			$('#update-tags-modale').show();
			$('select#tags-modale').prop("disabled", false);
			$('div#edit-modale.tags').hide();
			$('div#update-modale.tags').show();
		}
			
	);
	$('select#tags-modale').select2({
		tags: true,
		multiple: true,
        minimumInputLength: 1,
		ajax: {
			url: "/monsters/json/tags",
			dataType: "json",
			type: "GET",
			data: function (params) {

				var queryParameters = {
					name: params.term
				}
				return queryParameters;
			},
			processResults: function (data) {
				//console.log(data);
				return {
					results: $.map(data, function (item) {
						return {
							text: item.name,
							id: item.name
						}
					})
				};
			}
		}
    });


}); 
</script>

app/views/monsters/add_pair_tag.js.erb
$(document).ready(function(){
	$('select#tags-modale').prop("disabled", true);
	$('div#edit-modale.tags').show();
	$('div#update-modale.tags').hide();
	
	$("select#tags-modale").empty();
	<% @tags.each do |t| %>
		$("select#tags-modale").append('<option selected="selected" value="<%= t %>"><%= t %></option>');
	<% end %>
	$("select#tags-modale").trigger("change");
}); 

app/views/monsters/add_tag.js.erb
$(document).ready(function(){
	$('select.tags').prop("disabled", true);
	$('div#edit.tags').show();
	$('div#update.tags').hide();
	$("select.tags").empty();
	<% @tags.each do |t| %>
		$("select.tags").append('<option selected="selected" value="<%= t %>"><%= t %></option>');
	<% end %>
	$("select.tags").trigger("change");
}); 

app/views/monsters/auto_suggestion.js.erb
$(document).ready(function(){
	$("div.content.auto-suggestion").empty();
	$("div.content.auto-suggestion").append(`
		<% if @search_list != nil %>
			<% @search_list.each do |key, value| %>
				<div class="monster-list">
					<div class="panel panel-info">
						<div class="panel-heading"><%= key %></div>
						<div class="panel-body">
							<% value.each do |a, hash| %>
								<% if hash.length > 0 %>
									<div class="monster-list">
										<div class="panel panel-default">
											<div class="panel-heading"><%= a %></div>
											<div class="panel-body">
												<% hash.each do |m| %>
													<div class="panel panel-default monster panel-<%= rating_style(m["avg"]) %>">
														<div class="center-text panel-heading monster">
															<strong><%= link_to (m["avg"].to_s + " <span style=""font-weight:normal;"">(" + m["avg_count"].to_s + ")</span>").html_safe, detail_monsters_path(leader_id: @monster.id, sub_id: m["id"], type: "ls"), remote:true %></strong>
														</div>														
														<div class="panel-body">
															<%= link_to image_tag(m["url"], class: "center-image", :border => 0, :title => detailed_tooltip(m["id"], nil, nil), :alt => m["name"], size: '60'), monster_path(m["id"]) %>
														</div>
													</div>
												<% end %>
											</div>
										</div>
									</div>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>
	`);
	$('div.monster-list.auto-suggestion div.panel-body').unblock(); 
}); 

app/views/monsters/detail.html.erb
<%= render partial: 'monsters/show/detail' %>

app/views/monsters/detail.js.erb
$modal = $('.modal'),
$modalBody = $('.modal .modal-body'),
$modalHeading = $('.modal .modal-title');
$modalHeading.html('Details');
$modalBody.html("<%= escape_javascript(render partial: 'monsters/show/detail', leader_id: @leader_id, sub_id: @sub_id, type: @type) %>");
$modal.modal();

app/views/monsters/dungeons.html.erb
<%= @dungeons_hash %>

<br><br>
<% @dungeon_groups.each do |d| %>
<%= d %><br><br>
<% end %>

app/views/monsters/index.html.erb
<div class="center center-text">
	<h1>Search Monsters</h1>
</div>

<div class="body-search large_monster_input center">
	<p><input id="monster_field" class="monster typeahead main form-control center" type="text" placeholder="Monster Name"></p>
</div>

<div class="front-page wrapper">
	<div class="front-page section">
		<%= render partial: 'monsters/index/fp1', locals: {votes: @latestVotes} %>
	</div>
	<div class="front-page section">
		<%= render partial: 'monsters/index/fp2', locals: {votes: @latestVotesLl} %>
	</div>
	<div class="front-page section">
		<%= render partial: 'monsters/index/fp3', locals: {monsters: @topMonsters} %>
	</div>
	<div class="front-page section">
		<%= render partial: 'monsters/index/fp4', locals: {users: @topUsers} %>
	</div>
	<div class="front-page section">
		<%= render partial: 'monsters/index/fp5', locals: {comments: @latestComments} %>
	</div>
	<div class="front-page section">
		<%= render partial: 'monsters/index/fp6', locals: {comments: @latestCommentsLl} %>
	</div>
</div>	

app/views/monsters/questionable.html.erb
<div class="center center-text">
	<h1>Questionable Votes</h1>
</div>

<div class="front-page wrapper">
	<div class="front-page section">
		<%= render partial: 'monsters/questionable/outliers', locals: {votes: @outliers} %>
	</div>
	<div class="front-page section">
		<%= render partial: 'monsters/questionable/lowcount', locals: {votes: @low_count} %>
	</div>
	<div class="front-page section">
		<%= render partial: 'monsters/questionable/lowrating', locals: {votes: @low_rating} %>
	</div>
	<div class="front-page section">
		<%= render partial: 'monsters/questionable/lowrarity', locals: {votes: @low_rarity} %>
	</div>
</div>	

app/views/monsters/search.html.erb
<% #Valid variables %>
<% #@monsters: Monsters returned by matching tags %>

<div class="tags-container">
	<!-- Left Panel -->
	<div class="panel-left col-md-5">
		<!-- Tags -->
		<div class="monster-list">
			<div class="panel panel-default">
				<div class="panel-heading">Tags</div>
				<div class="panel-body">
					<div class="tag-section">
						<%= form_tag(tags_monsters_path(), method: "get") do %>
							<div>
								<p><select multiple="true" name="tags[]" class="tags select2">
									<% if @selected != nil %>
										<% @selected.each do |t| %>
											<option selected="selected" value="<%= t %>"><%= t %></option>
										<% end %>
									<% end %>
								</select></p>
								<button type="submit">Search</button>
								<button id="reset" type="reset" value="Reset">Reset</button>
							</div>
						<% end %>
					</div>
					
					<div class="tag-section select">
						<select id="tag_list" name="tag_list" size="8">
							<% @tags.each do |t| %>
								<option value="<%= t.name %>"><%= t.name %> (<%= t.taggings_count %>) </option>
							<% end %>
						</select>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Right Panel -->
	<div class="panel-right col-md-7">
		<!-- Results -->
		<div class="monster-list">
			<div class="panel panel-default">
				<div class="panel-heading">Results <%= if @monsters != nil then "(" + @monsters.size.to_s + ")" else "( 0 )" end %></div>
				<div class="monster-container panel-body">
					<div>
						<% if @monsters != nil %>
							<% @monsters.each do |m| %>
								<%= link_to image_tag(fetch_monster_url_by_id_json(m["id"]), :border => 0, :title => detailed_tooltip(m["id"], nil, nil), size: '60'), fetch_monster_by_id(m["id"]) %>
							<% end %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/monsters/show.html.erb
<% #Valid variables %>
<% #@monster: hash of current monster from json %>
<% #@monster: monster object %>
<% #@active_skill: hash of active skill from json %>
<% #@leader_skill: hash of leader skill from json %>
<% #@awakenings: array of hash of awoken skills from json %>
<% #@subs: array of hash of subs from json %>
<% #@leaders: array of hash of leaders from json %>
<% #@related: array of monster objects for evolutions %>

<!-- Make a Suggestion -->
<%= render partial: "monsters/show/jumbotron" %>

<div class="monster-container">
	<div class="panel-left section col-md-7">
		<!-- Suggested Subs -->
		<%= render partial: "monsters/show/suggestion", :locals => {sugg: @subs, monster: @monster, option: "sub"} %>

		<!-- Suggested Leader/Leader Pairing -->
		<%= render partial: "monsters/show/suggestion", :locals => {sugg: @ll, monster: @monster, option: "ll"} %>
		
		<!-- Suggested Leader -->
		<%= render partial: "monsters/show/suggestion", :locals => {sugg: @leaders, monster: @monster, option: "leader"} %>

	</div>
	
	<div class="panel-right section col-md-5">
		<!-- Make a Suggestion -->
		<%= render partial: "monsters/show/make_suggestion" %>

		<!-- Voting Guidelines -->
		<%= render partial: "monsters/show/guidelines" %>
		
		<!-- Tags -->
		<%= render partial: "monsters/show/tags" %>
			
		<!-- Related Evolutions -->
		<%= render partial: "monsters/show/evolutions" %>
	</div>
</div>

<%= render partial: "monsters/show/monster_link" %>

<% if @attr_main != nil and  %>
	<!-- Auto Suggestion -->
	<%= render partial: "monsters/show/autosuggestion" %>
<% end %>


<!-- Modale -->
<div class="modal fade" id="vote_details" tabindex="-1" role="dialog" aria-labelledby="vote_details" aria-hidden="true">
	<div class="modal-dialog">
	  <div class="modal-content">
		<div class="modal-header">
		  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		  <h4 class="modal-title"></h4>
		</div>
		<div class="modal-body">
		</div>
		<div class="modal-footer">
		  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
	  </div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->