config/routes.rb
Rails.application.routes.draw do
	get '/about', controller: 'news', action: 'about'
	get '/privacy', controller: 'news', action: 'privacy'
	
	resources :dungeons do
		get 'json/normal' => "dungeons#get_normal_dungeons", on: :collection
		get 'json/special' => "dungeons#get_special_dungeons", on: :collection 
		get 'json/technical' => "dungeons#get_technical_dungeons", on: :collection 
		get 'json/multiplayer' => "dungeons#get_multiplayer_dungeons", on: :collection
	end
	
	resources :ml_ratings, only: [:create]
	
	resources :monster_links
	
    resources :news

	resources :c_ratings, except: [:edit, :update, :destroy, :new, :show]
	resources :c_ll_ratings, except: [:edit, :update, :destroy, :new, :show]
		
	resources :comments,  except: [:edit, :update, :new, :show]
	resources :comment_lls,  except: [:edit, :update, :new, :show]

	resources :votes, except: [:edit, :update, :destroy, :new] do
		get 'statistics' , controller: 'votes', action: 'statistics', on: :collection 
	end
	resources :vote_lls, except: [:edit, :update, :destroy, :new]

	resources :monsters, except: [:destroy, :new, :create, :update, :edit] do
		get 'json/tags', controller: 'monsters', action: 'tags_json', on: :collection 
		get 'json/typeahead', controller: 'monsters', action: 'typeahead_json', on: :collection 
		get 'json/subs/:id', controller: 'monsters', action: 'subs_json', on: :collection 
		get 'json/graph', controller: 'monsters', action: 'graph_json', on: :collection
		get 'detail' , controller: 'monsters', action: 'detail', on: :collection 
		get 'tag', controller: 'monsters', action: 'add_tag'
		get 'tag/pair', controller: 'monsters', action: 'add_pair_tag'
		get 'tags', controller: 'monsters', action: 'search', on: :collection
		get 'tags/update', controller: 'monsters', action: 'tag_update', on: :collection
		get 'questionable', controller: 'monsters', action: 'questionable', on: :collection
		get 'autosuggestion', controller: 'monsters', action: 'auto_suggestion'
	end

	devise_for :users
	
	
	match '/static/img/monsters/:size/:id.:basename.png' => "monsters#image_proxy", via: [:get]
	
	root 'news#index'

end

app/models/c_rating.rb
class CRating < ActiveRecord::Base
	belongs_to :comment
	belongs_to :user
	validates :comment_id, :user_id, :score, presence: true
	validates_uniqueness_of :comment_id, scope: :user_id
	
	def self.model_gen(t)
  		case t
			when "ls"
				return CRating
			when "ll"
				return CLlRating
		end
	end
end

app/controllers/c_ratings_controller.rb
class CRatingsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  respond_to :html

  def find_rating(m1_id, m2_id, t)
	case t
		when "ls"
			return Comment.where(leader_id: m1_id, sub_id: m2_id, user_id: current_user.id).first
		when "ll"
			return Comment.where(Monster.query_gen(m1_id, m2_id, t) + "and user_id = ?", m1_id, m2_id, current_user.id).first
	end
  end
  def create
	t = params["type"]
	if t != nil		
		p = c_rating_params
		
		if t == "ls"
			c_rating = CRating.model_gen(t).new(p)
			query = {comment_id: p["comment_id"], user_id: current_user.id}
			comment = c_rating.comment
			m1 = comment.leader_id
			m2 = comment.sub_id
		elsif t == "ll"
			c_rating = CRating.model_gen(t).new(comment_ll_id: p["comment_id"], score: p["score"])
			query = {comment_ll_id: p["comment_id"], user_id: current_user.id}
			comment = c_rating.comment_ll
			m1 = comment.leaders[0]
			m2 = comment.leaders[1]
		end
		score = p["score"].to_i
		old = CRating.model_gen(t).where(query).first
		if score == 1 or score == -1
			if current_user.id != comment.user_id then
				if old != nil then
					old.score = score
					if old.save
						flash.now[:notice] = 'Vote updated'
					else
						flash.now[:alert] = 'Could not rate comment'
					end
				else
					c_rating.user_id = current_user.id
					if c_rating.save
						flash.now[:notice] = 'Comment rated'
					else
						flash.now[:alert] = 'Could not rate comment'
					end
				end
			else
				flash.now[:alert] = 'Could not rate comment'
			end
		else
			flash.now[:alert] = 'Could not rate comment'
		end
		redirect_to detail_monsters_path(leader_id: m1, sub_id: m2, tab: 2, type: t), anchor: comment.id, notice: flash[:notice], alert: flash[:alert]
	else
		render_404
	end
  end

  def update
    @c_rating.update(c_rating_params)
    respond_with(@c_rating)
  end

  private
    def c_rating_params
      params.permit(:comment_id,:score)
    end
end

app/helpers/c_ratings_helper.rb
module CRatingsHelper
end

app/views/c_ratings/_form.html.erb
<%= form_for(@c_rating) do |f| %>
  <% if @c_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@c_rating.errors.count, "error") %> prohibited this c_rating from being saved:</h2>

      <ul>
      <% @c_rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :comment_id %><br>
    <%= f.number_field :comment_id %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/c_ratings/edit.html.erb
<h1>Editing c_rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @c_rating %> |
<%= link_to 'Back', c_ratings_path %>

app/views/c_ratings/index.html.erb
<h1>Listing c_ratings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @c_ratings.each do |c_rating| %>
      <tr>
        <td><%= c_rating.user_id %></td>
        <td><%= c_rating.comment_id %></td>
        <td><%= c_rating.score %></td>
        <td><%= link_to 'Show', c_rating %></td>
        <td><%= link_to 'Edit', edit_c_rating_path(c_rating) %></td>
        <td><%= link_to 'Destroy', c_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New C rating', new_c_rating_path %>

app/views/c_ratings/new.html.erb
<h1>New c_rating</h1>

<%= render 'form' %>

<%= link_to 'Back', c_ratings_path %>

app/views/c_ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @c_rating.user_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @c_rating.comment_id %>
</p>

<p>
  <strong>Score:</strong>
  <%= @c_rating.score %>
</p>

<%= link_to 'Edit', edit_c_rating_path(@c_rating) %> |
<%= link_to 'Back', c_ratings_path %>