config/routes.rb
Rails.application.routes.draw do
	get '/about', controller: 'news', action: 'about'
	get '/privacy', controller: 'news', action: 'privacy'
	
	resources :dungeons do
		get 'json/normal' => "dungeons#get_normal_dungeons", on: :collection
		get 'json/special' => "dungeons#get_special_dungeons", on: :collection 
		get 'json/technical' => "dungeons#get_technical_dungeons", on: :collection 
		get 'json/multiplayer' => "dungeons#get_multiplayer_dungeons", on: :collection
	end
	
	resources :ml_ratings, only: [:create]
	
	resources :monster_links
	
    resources :news

	resources :c_ratings, except: [:edit, :update, :destroy, :new, :show]
	resources :c_ll_ratings, except: [:edit, :update, :destroy, :new, :show]
		
	resources :comments,  except: [:edit, :update, :new, :show]
	resources :comment_lls,  except: [:edit, :update, :new, :show]

	resources :votes, except: [:edit, :update, :destroy, :new] do
		get 'statistics' , controller: 'votes', action: 'statistics', on: :collection 
	end
	resources :vote_lls, except: [:edit, :update, :destroy, :new]

	resources :monsters, except: [:destroy, :new, :create, :update, :edit] do
		get 'json/tags', controller: 'monsters', action: 'tags_json', on: :collection 
		get 'json/typeahead', controller: 'monsters', action: 'typeahead_json', on: :collection 
		get 'json/subs/:id', controller: 'monsters', action: 'subs_json', on: :collection 
		get 'json/graph', controller: 'monsters', action: 'graph_json', on: :collection
		get 'detail' , controller: 'monsters', action: 'detail', on: :collection 
		get 'tag', controller: 'monsters', action: 'add_tag'
		get 'tag/pair', controller: 'monsters', action: 'add_pair_tag'
		get 'tags', controller: 'monsters', action: 'search', on: :collection
		get 'tags/update', controller: 'monsters', action: 'tag_update', on: :collection
		get 'questionable', controller: 'monsters', action: 'questionable', on: :collection
		get 'autosuggestion', controller: 'monsters', action: 'auto_suggestion'
	end

	devise_for :users
	
	
	match '/static/img/monsters/:size/:id.:basename.png' => "monsters#image_proxy", via: [:get]
	
	root 'news#index'

end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  require 'open-uri'
  require 'open_uri_redirections'
  before_action :cache_data
  #before_action :set_monster, only: [:auto_suggestion]
  before_action :fetch_both, only: [:detail, :graph_since_json, :graph_monthly_json, :graph_count_json, :graph_weight_json, :graph_json ]
  before_action :authenticate_user!, only: [:add_tag, :add_pair_tag, :tag_update]
  respond_to :html
  
  def questionable
	Rails.cache.fetch("questionable_outliers", expires_in: 15.minutes) do
			Vote.outliers(Rails.application.config.vote_display_default, "ls")
	end
	Rails.cache.fetch("questionable_low_count", expires_in: 15.minutes) do
			Vote.low_count(Rails.application.config.vote_display_default, "ls")
	end
	Rails.cache.fetch("questionable_low_rating", expires_in: 15.minutes) do
			Vote.low_rating(Rails.application.config.vote_display_default, "ls")
	end
	Rails.cache.fetch("questionable_low_rarity", expires_in: 15.minutes) do
			Vote.find_monster_in(fetch_low_rarity_json, Rails.application.config.vote_display_default, "ls")
	end
	#@outliers = Vote.outliers(Rails.application.config.vote_display_default, "ls")
	#@low_count = Vote.low_count(Rails.application.config.vote_display_default, "ls")
	#@low_rating = Vote.low_rating(Rails.application.config.vote_display_default, "ls")
	@outliers = Rails.cache.fetch("questionable_outliers")
	@low_count = Rails.cache.fetch("questionable_low_count")
	@low_rating = Rails.cache.fetch("questionable_low_rating")
	@low_rarity = Rails.cache.fetch("questionable_low_rarity")
  end

  def fetch_low_rarity_json
	monsters = Rails.cache.fetch("monster")
	results = Array.new
	monsters.each do |m|
		if m["rarity"] < 5 then results.push(m["id"]) end
	end
	return results
  end
  
  def image_proxy
	remote_url = Rails.application.config.img_path_monsters + "#{request.path}"
	local_url = "public#{request.path}"
  
	if not File.exist? local_url
		IO.copy_stream(open(remote_url, :allow_redirections => :safe), local_url)
	end
 
	send_file local_url, type: 'image/png', disposition: 'inline'
  end
	
  def search
	@title = "Tags"
	@tags = ActsAsTaggableOn::Tag.order(:name)
	@selected = params[:tags]
	if @selected != nil and @selected.size > 0
		monsters = Monster.tagged_with(@selected, :on => :tags)
		if monsters != nil and monsters.length > 500
			monsters = monsters[0..499]
			flash.now[:alert] = 'Showing first 500 results. Add more tags to narrow search.'
		end
		@monsters = fetch_monster_json_by_array(monsters)
		if @monsters != nil then @monsters = @monsters.sort_by { |hash| hash['element'].to_i } end 
	end
  end
  
  def index
	@title = "Summary"
	@latestVotes = Vote.order(created_at: :desc).limit(Rails.application.config.fp_display_max_monsters)
	@latestVotesLl = VoteLl.order(created_at: :desc).limit(Rails.application.config.fp_display_max_monsters)
	
	topMonstersArray = Vote.recent_top(Rails.application.config.vote_display_default)
	@topMonsters = Array.new
	topMonstersArray.each do |m|
		@topMonsters.push([fetch_monster_by_id(m[0]),m[1]])
	end
	
	@topUsers = User.top
	@latestComments = Comment.latest
	@latestCommentsLl = CommentLl.latest
  end
  
  #Shows a particular monster from JSON. Input parameter is params[:id]
  def show
	@monster = fetch_monster_by_id(params[:id])

	#Make sure monster was fetched
	if @monster != nil
		update_monster_name_with_json(@monster)
		@monster.url = fetch_monster_url_by_id_json(@monster.id)
		
		@title = @monster.id.to_s
		
		@subs = Array.new
		#Get suggested subs
		@subs_list = @monster.subs
		@subs_list = @subs_list.sort_by { | x | x[:score] }.reverse
		@subs_list.each do |s|
			sub = fetch_monster_by_id(s[:id])
			if sub != nil
				sub.avg = round?(s[:score])
				sub.avg_count = @monster.vote_count(sub.id,"ls")
				sub.url = fetch_monster_url_by_id_json(sub.id)
				if user_signed_in? and user_voted_default_month(@monster.id,sub.id,"ls")
					sub.user_score = fetch_user_vote_by_default_month(@monster.id, sub.id,"ls").score
				end
				@subs.push(sub)
			end
		end
		
		@leaders = Array.new
		#Get suggested leaders
		@leaders_list = @monster.leaders
		@leaders_list = @leaders_list.sort_by { | x | x[:score] }.reverse
		@leaders_list.each do |l|
			leader = fetch_monster_by_id(l[:id])
			if leader != nil
				leader.avg = round?(l[:score])
				leader.avg_count = leader.vote_count(@monster.id,"ls")
				leader.url = fetch_monster_url_by_id_json(leader.id)
				if user_signed_in? and user_voted_default_month(leader.id,@monster.id,"ls")
					leader.user_score = fetch_user_vote_by_default_month(leader.id,@monster.id,"ls").score
				end
				@leaders.push(leader)
			end
		end
		
		@ll = Array.new
		@ll_list = @monster.ll_list
		@ll_list = @ll_list.sort_by { | x | x[:score] }.reverse
		@ll_list.each do |l|
			leader = fetch_monster_by_id(l[:id])
			if leader != nil
				leader.avg = round?(l[:score])
				leader.url = fetch_monster_url_by_id_json(leader.id)
				leader.avg_count = @monster.vote_count(leader.id,"ll")
				if user_signed_in? and user_voted_default_month(@monster.id,leader.id,"ll")
					leader.user_score = fetch_user_vote_by_default_month(@monster.id,leader.id,"ll").score
				end
				@ll.push(leader)
			end
		end
		
		#Get other details
		@active_skill = fetch_active_skill_by_id_json(@monster.id)
		@leader_skill = fetch_leader_skill_by_id_json(@monster.id)
		@awakenings = fetch_awakenings_by_id_json(@monster.id)
		@related = append_monster_url(get_all_evo(@monster.id))
		@tags = @monster.tag_list.sort
		@links = @monster.monster_links.order(updated_at: :desc)
		
		tags = @monster.tag_list.sort
		
		#Rarity
		@rarity = "rarity: over 5"
		
		#Elements
		@attr_main = tags.select {|tag| tag.include? 'attr main:'}[0]
		if @attr_main != nil then 
			@elem_main = @attr_main.split('attr main: ')[1]
			@attr_elem1 = "attr: " + @elem_main
		end
		@attr_sub = tags.select {|tag| tag.include? 'attr sub:'}[0]
		if @attr_sub != nil
			@elem_sub = @attr_sub.split('attr sub: ')[1] 
			@attr_elem2 = "attr: " + @elem_sub
		end
		
		if @attr_main != nil then @check_main = "checked" end
		@check_sub = ""
		@check_elem1 = ""
		@check_elem2 = ""
		@check_rarity = "checked"
		
		#Type
		@type = tags.select {|tag| tag.include? 'type:'}
		@check_type = Array.new
		@type.each do |t|
			type = t.split('type: ')[1]
			if @leader_skill != nil
				if @leader_skill["effect"].downcase.include? type then @check_type.push(t) end
			end
		end
				
		#Awakenings
		@check_awoken_skills = Array.new
		@awoken_skills = tags.select {|tag| tag.include? 'awoken skill:'}
		if not @awoken_skills.include? 'awoken skill: recover bind' then @awoken_skills.push('awoken skill: recover bind') end
		if not @awoken_skills.include? 'awoken skill: resistance-bind' then @awoken_skills.push('awoken skill: resistance-bind') end
		if not @awoken_skills.include? 'awoken skill: two-pronged attack'
			@awoken_skills.push('awoken skill: two-pronged attack')
		else
			@check_awoken_skills.push('awoken skill: two-pronged attack')
		end
		if @elem_main != nil and not @awoken_skills.include? 'awoken skill: enhanced ' + @elem_main + ' att.'
			@awoken_skills.push('awoken skill: enhanced ' + @elem_main + ' att.')
		elsif @elem_main != nil and @awoken_skills.include? 'awoken skill: enhanced ' + @elem_main + ' att.'
			@check_awoken_skills.push('awoken skill: enhanced ' + @elem_main + ' att.')
		end
		if @elem_sub != nil and not @awoken_skills.include? 'awoken skill: enhanced ' + @elem_sub + ' att.'
			@awoken_skills.push('awoken skill: enhanced ' + @elem_sub + ' att.')
		elsif @elem_sub != nil and @awoken_skills.include? 'awoken skill: enhanced ' + @elem_sub + ' att.' and @elem_sub != @elem_main
			@check_awoken_skills.push('awoken skill: enhanced ' + @elem_sub + ' att.')
		end
		@awoken_skills.sort!

	else
		render_404; return;
	end
	
    respond_with(@monster)
  end
  
  def auto_suggestion
	filter = params["filter"]
	
	if filter == nil then return end
	
	@monster = Monster.find(params["monster_id"])
	if @monster != nil
		#Get tags
		tags = @monster.tag_list.sort
		
		#Get elements
		attr_main = tags.select {|tag| tag.include? 'attr main:'}[0] #attr main: fire
		
		if attr_main == nil then return end
		
		if attr_main != nil then elem_main = attr_main.split('attr main: ')[1] end #fire
		attr_sub = tags.select {|tag| tag.include? 'attr sub:'}[0] #attr sub: water
		if attr_sub != nil then elem_sub = attr_sub.split('attr sub: ')[1] end #water
		
		exclude = ["type: awoken skill material","type: enhance material","type: evo material"] #Exclude all tags in this array
		
		#Get Leader Skill
		leader_number_colors = 0 #Leader requires 0 colors to activate skill
		
		color_match = tags.grep(/leader skill: color match - [1-9] colors/) #Find tag which determines number of colors the leader needs
		if color_match.length == 1 then #If a match was found and an array was returned with exactly 1 result
			leader_number_colors = color_match[0].split('leader skill: color match - ')[1].split(' colors')[0] #Get the number from the tag
			if is_number? leader_number_colors then #If it is a number
				leader_number_colors = leader_number_colors.to_i #Convert from string to int
				leader_colors = tags.grep(/leader skill: color match - [a-z]/).each do |c| c.gsub!('leader','active').gsub!('color match','change board') end #Get all of the colors this leader requires
			end
		end
		
		#Filters
		
		#Utility
		utility = [
			'active skill: damage reduction',
			'active skill: defense reduction',
			'active skill: delay',
			'active skill: avoid damage',
			'active skill: bind recovery',
			'active skill: poison damage',
			'active skill: atk buff'
		]
		
		#Orb Change
		orb_change = ['active skill: change orbs - ' + elem_main]
		if attr_sub != nil then orb_change.push('active skill: change orbs - ' + elem_sub) end
		orb_change.push('active skill: spawn')
		orb_change.push('active skill: skyfall')
		
		#Board Change
		board_change = Array.new
		if leader_number_colors == 0

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/monsters/show/_autosuggestion.html.erb
	<div class="monster-container">
		<div class="monster-list col-md-12 auto-suggestion">
			<div class="panel panel-default">
				<div class="panel-heading">Auto-Suggestions</div>
				<div class="panel-body">
					<%= form_tag(monster_autosuggestion_path(@monster.id), method: "get", remote: true) do %>
						<table class="table">
							<tr>
								<td>
									<% if @attr_main != nil %><input type="checkbox" aria-label="..." name="filter[]" value="<%= @attr_main %>" <%= @check_main %>><%= @attr_main %><br><% end %>
									<% if @attr_sub != nil %><input type="checkbox" aria-label="..." name="filter[]" value="<%= @attr_sub %>" <%= @check_sub %>><%= @attr_sub %><br><% end %>
									<% if @attr_elem1 != nil %><input type="checkbox" aria-label="..." name="filter[]" value="<%= @attr_elem1 %>" <%= @check_elem1 %>><%= @attr_elem1 %><br><% end %>
									<% if @attr_elem2 != nil %><input type="checkbox" aria-label="..." name="filter[]" value="<%= @attr_elem2 %>" <%= @check_elem2 %>><%= @attr_elem2 %><br><% end %>
									<input type="checkbox" aria-label="..." name="filter[]" value="<%= @rarity %>" <%= @check_rarity %>><%= @rarity %><br>
									<% @type.each do |t| %>
										<% if @check_type.include? t then checked="checked" else checked="" end %>
										<input type="checkbox" aria-label="..." name="filter[]" value="<%= t %>" <%= checked %>><%= t %><br>
									<% end %>
								</td>
								<td>
									<% @awoken_skills.each do |a| %>
										<% if @check_awoken_skills.include? a then checked = "checked" else checked = "" end %>
										<input type="checkbox" aria-label="..." name="filter[]" value="<%= a %>" <%= checked %>><%= a %><br>
									<% end %>
								</td>
							</tr>
						</table>	
						<%= button_tag "Refresh", class: "btn btn-default auto-suggestion" %>
					<% end %>
					<br>
					<div class="content auto-suggestion">
					</div>				
				</div>
			</div>
		</div>
	</div>

app/views/monsters/show/_commentbox.html.erb
<div class="clear-left">
<%= form_tag({controller: "comments", action: "create", params: {leader_id: @leader.id, type: @type, sub_id: @sub.id}}) do  %>
  <div>
	<%= text_area_tag(:comment_text, nil,size: "60x5") %>
	<br>
	<%= submit_tag("Create Comment") %>
  </div>
<% end %>
</div>

app/views/monsters/show/_detail.html.erb
<div>
	<div class="panel panel-default monster details">
		<div class="center-text panel-heading monster">
			<strong>Leader</strong>
		</div>
		<div class="panel-body">
			<%= link_to image_tag(@leader_details["image60_href"].to_s, :border => 0, :title => @leader.tooltip), monster_path(@leader.id) %>
		</div>
	</div>
	<div class="panel panel-default monster details">
		<div class="center-text panel-heading monster">
			<strong><% if @type == "ls" then concat "Sub" else concat "Leader" end %></strong>
		</div>
		<div class="panel-body">
			<%= link_to image_tag(@sub_details["image60_href"].to_s, :border => 0, :title => @sub.tooltip), monster_path(@sub.id) %>
		</div>
	</div>
	<div class="panel panel-default monster details summary">
		<div class="center-text panel-heading monster">
			<strong>Details</strong>
		</div>
		<div class="panel-body">
			<table width=100% height=100%>
				<tr>
					<td><span class="badge">Current</span></td>
					<td><span class="label label-<%= rating_style(@score) %>"><%= round?(@score) %> out of <%= Rails.application.config.vote_rating_max %></span><span class="label label-primary"><%= @votes %> votes</span></td>
				</tr>
				<tr>
					<td><span class="badge">All Time</span></td>
					<td><span class="label label-<%= rating_style(@score_all) %>"><%= round?(@score_all) %> out of <%= Rails.application.config.vote_rating_max %></span><span class="label label-primary"><%= @votes_all %> votes</span></td>
				</tr>
			</table>
		</div>
	</div>
	<div class="panel panel-default monster tags details">
		<div class="center-text panel-heading monster tags">
			<strong>Pairing Specific Tags</strong>
		</div>
		<div class="panel-body tags">
			<%= form_tag(monster_tag_pair_path(@leader.id, m2_id: @sub.id, type: @type), method: "get", remote:true ) do %>
				<div>
					<p><select id="tags-modale" style="width:100%;" disabled multiple="true" name="tags[]" class="tags select2">
					<% if @type == "ll" %>
						
						<% if @leader.id <= @sub.id %>
							<% m1 = @leader %>
							<% m2 = @sub %>
						<% else %>
							
							<% m1 = @sub %>
							<% m2 = @leader %>
						<% end %>
					<% else %>
							<% m1 = @leader %>
							<% m2 = @sub %>
					<% end %>
					<% m1.tag_list_on(@type + "_" + m2.id.to_s).each do |t| %>
						<option selected="selected"><%= t %></option>
					<% end %>
					</select></p>
				</div>
				<% if user_signed_in? %>
					<div id="edit-modale" class="tags  button-container col-xs-3">
						<button type="button" id="edit-tags-modale" class="btn btn-default tags" aria-label="Left Align">Edit</button>
					</div>
					<div id="update-modale" class="tags  button-container col-xs-3">
						<%= submit_tag "Update", id:"update-tags-modale", class: "tags btn btn-default" %>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

<script>
	chart1(<%= @leader.id %>,<%= @sub.id %>,'<%= @type %>',['since','monthly','weighted'],'#chart1','Ratings',1,<%= Rails.application.config.vote_rating_max %>);
	chart1(<%= @leader.id %>,<%= @sub.id %>,'<%= @type %>',['count'],'#chart2','Ratings Count',null,null);
</script>


	<ul class="nav nav-tabs">
	  <li id="statistics" role="presentation" class="active"><a href="#">Statistics</a></li>
	  <li id="comments" role="presentation"><a href="#">Comments ( <%= @comments.count %> )</a></li>
	  <li style="display: none;" id="history" role="presentation"><a href="#">History</a></li>
	</ul>
	<div id="statistics" class="page-tab">
		<div id="chart1" style="width: 900px; height: 300px; margin: 0 auto"></div>
		<div id="chart2" style="width: 900px; height: 300px; margin: 0 auto"></div>
	</div>
	<div id="comments" class="page-tab">
		<% hidden = 0; option = "comment" %>
		<% @comments.each do |c| %>
			<div id="<%= c.id %>" class="panel panel-default comment <% if c.score < Rails.application.config.comment_low_score then hidden = 1; concat "low-score"; end %>">
				<div class="panel-body comment">
					<div class="c-rating comment">
						<% if user_signed_in? then %>
							<% if c.comment != "[deleted]" %>
								<p><%= link_to "", c_ratings_path(comment_id: c.id, score: 1, type: @type), method: :post, title: "Upvote", class: "glyphicon glyphicon-chevron-up" %></p>
								<%= link_to "", c_ratings_path(comment_id: c.id, score: -1, type: @type), method: :post, title: "Downvote", class: "glyphicon glyphicon-chevron-down" %>
							<% end %>
						<% end %>
					</div>
					<div class="comment comments">
						<%= c.comment %>
					</div>
				</div>
				<div class="panel-footer comment" style="overflow:hidden;">
					<span style="float:left"><%= c.user.username + " - 	" + time_ago_in_words(c.created_at) + " ago" %></span>
					<% if c.comment != "[deleted]" and user_signed_in? and (c.user_id == current_user.id or current_user.admin) %>
						<span style="float:right"><%= link_to 'Delete', c, method: :delete, data: { confirm: 'Are you sure?' } %></span>
					<% end %>
					<span style="float:right">Score: <%= c.score %></span>
				</div>
			</div>
		<% end %>
		<% if hidden == 1 %>
			<div style="padding:0;" class="col-md-2"><p><button type="button" id="<%= option %>" class="btn btn-default show-low" aria-label="Left Align">Show Hidden</button></p></div>
		<% end %>
		<% if user_signed_in? %>
			<%= render partial: 'monsters/show/commentbox' %>
		<% else %>
			<p>You must be <%= link_to "logged in", new_user_session_path() %> to comment</p>
		<% end %>
	</div>
	<div id="history" class="page-tab">
		History
	</div>


<%= render partial: 'monsters/show/modale' %>
<script>
	<% if params[:tab] == "2" %>
		$('div.page-tab').hide();
		$('.nav-tabs li').removeClass("active");
		$('.nav-tabs li#comments').addClass("active");
		$('div#comments.page-tab').show();
	<% else %>
		$('div#comments.page-tab').hide();
		$('div#history.page-tab').hide();
	<% end %>
</script>

app/views/monsters/show/_evolutions.html.erb
<!-- Related Evolutions -->
<div class="monster-list">
	<div class="panel panel-default">
		<div class="panel-heading">Related Evolutions</div>
		<div class="monster-container panel-body">
			<% @related.each do |m| %>
				<% if m != @monster %>
					<%= link_to image_tag(m.url, :border => 0, :title => m.tooltip), m %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/monsters/show/_monster_link.html.erb
<!-- Links -->
<div class="monster-list col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading">Links</div>
		<div class="panel-body">
			<% #if @links.length > 0 %>
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Link</th>
							<th>Type</th>
							<th>Date</th>
							<th>Version</th>
							<th>Submitter</th>
							<th>Like</th>
						</tr>
					</thead>
					<tbody>
						<% @links.each do |l| %>
							<tr>
								<td><%= link_to l.title, l.url %></td>
								<td><%= l.link_type.capitalize %></td>
								<td><%= l.updated_at.strftime("%m-%d-%Y") %></td>
								<td><%= l.version.number %></td>
								<td><%= l.user.username %></td>
								<td id="ml_<%= l.id %>">
									<% if user_signed_in? and l.user == current_user %>
										<b><%= l.ml_ratings.sum(:score)%></b>
										<%= link_to "Edit", edit_monster_link_path(l.id) %>
									<% else %>
										<% if user_signed_in? and current_user.ml_ratings.where(monster_link_id: l.id).count >= 1 %>
											<b><%= l.ml_ratings.sum(:score)%></b>
										<% else %>
											<%= link_to l.ml_ratings.sum(:score), ml_ratings_path(monster_link_id: l.id), method: :post %>
										<% end %>
									<% end %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			<% #end %>
			<div class="col-sm-3">
				<%= link_to "Submit New Link", new_monster_link_path(monster_id: @monster.id) %>
			</div>
		</div>
	</div>
</div>

app/views/monsters/show/_suggestion.html.erb
<div class="monster-list" style="display:block;">
	<div class="panel panel-default">
		<div class="panel-heading">
			<%
			case option
				when "sub"
					concat "Suggested Subs"
				when "leader"
					concat "Ratings as Sub"
				when "ll"
					concat "Leader/Leader Pairing"
			end
			%>
			
		</div>
		<div class="monster-container panel-body">
			<div class="shown">
				<% if sugg != nil %>
					<% hidden = 0 %>
					<% sugg.each do |s| %>
						<%
							case option
								when "sub"
									m1_id = @monster.id
									m2_id = s.id
									controller = "votes"
									type = "ls"
								when "leader"
									m1_id = s.id
									m2_id = @monster.id
									controller = "votes"
									type = "ls"
								when "ll"
									m1_id = @monster.id
									m2_id = s.id
									controller = "vote_lls"
									type = "ll"
							end

							if s.avg < Rails.application.config.vote_low_score and hidden == 0
								hidden = 1
							end
						%>
						<div class="panel panel-<%= rating_style(s.avg) %> monster <% if hidden == 1 %>low-score <%= option %><% end %>">
							<div class="center-text panel-heading monster">
								<strong><%= link_to (s.avg.to_s + " <span style=""font-weight:normal;"">(" + s.avg_count.to_s + ")</span>").html_safe, detail_monsters_path(leader_id: m1_id, sub_id: m2_id, type: type), remote:true %></strong>
							</div>
							<div class="panel-body">
								<%= link_to image_tag(s.url.to_s, class: "center-image", :border => 0, :title => detailed_tooltip(s.id, @monster.id, option), size: '60'), monster_path(s.id) %>
							</div>
							<% if user_signed_in? %>
								<div class="dropdown">
									<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
										<% if s.user_score != nil then %><%= s.user_score %><% else %>Vote<% end %>
										<span class="caret"></span>
									</button>
									<ul class="vote dropdown-menu" aria-labelledby="dropdownMenu">
										<% for i in Rails.application.config.vote_rating_max.downto(1) %>
											<li><%= link_to i.to_s, {controller: controller, action: "create", current_id: monster.id, monster_id: s.id, rating: i, commit: option}, method: "post" %></li>
										<% end %>
										<% if s.user_score != nil %>
											<li><%= link_to "-", {controller: controller, action: "create", current_id: monster.id, monster_id: s.id, rating: 0, commit: option}, method: "post" %></li>
										<% end %>
									</ul>
								</div>
							<% end %>
						</div>
					<% end %>
				<% end %>
			</div>
			<% if hidden == 1 %>
				<button type="button" id="<%= option %>" class="btn btn-default show-low" aria-label="Left Align">Show Hidden</button>
			<% end %>
		</div>
	</div>
</div>

app/views/monsters/show/_tags.html.erb
<!-- Tags -->
<div class="monster-list">
	<div class="panel panel-default">
		<div class="panel-heading">Tags</div>
		<div class="panel-body">
			<div>
				<%= form_tag(monster_tag_path(@monster.id), method: "get", remote:true ) do %>
					<div>
						<p><select disabled multiple="true" name="tags[]" class="tags select2">
						<% @tags.each do |t| %>
							<option selected="selected"><%= t %></option>
						<% end %>
						</select></p>
					</div>
					<% if user_signed_in? %>
						<div id="edit" class="tags button-container col-xs-3">
							<button type="button" id="edit-tags" class="btn btn-default tags" aria-label="Left Align">Edit</button>
						</div>
						<div id="update" class="tags button-container  col-xs-3">
							<%= submit_tag "Update", id:"update-tags", class: "tags btn btn-default" %>
						</div>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>